name = "imgbed"
compatibility_date = "2024-04-01"
pages_build_output_dir = "./"

# 绑定kv
[[kv_namespaces]]
binding = "img_url"
id = "c2d2c0fc3bcf49c1aa0bb5c2337f489f"

# R2 绑定
[[r2_buckets]]
binding = "img_r2"
bucket_name = "img-r2-bucket"
